import type { EnemyDefinition, HeroClass, LevelDefinition } from "./types";

export const heroClasses: HeroClass[] = [
  {
    id: "berserker",
    name: "Berserker",
    fantasy: "A reckless melee bruiser who turns attack speed into carnage.",
    combatStyle: "Fast cleaves, high crits, low defenses",
    color: "#ef4444",
    damageKind: "melee",
    stats: {
      health: 190,
      armor: 10,
      damage: 31,
      attackSpeed: 1.45,
      range: 1.8,
      critChance: 0.22,
      critDamage: 1.85,
      abilityPower: 0,
      cooldownReduction: 0,
    },
    special: {
      name: "Whirlwind Cut",
      description: "Every fourth attack slashes several nearby enemies.",
      everyNthAttack: 4,
      cleaveTargets: 4,
      damageMultiplier: 0.78,
    },
  },
  {
    id: "arcanist",
    name: "Arcanist",
    fantasy: "A spellcaster who burns grouped enemies with volatile magic.",
    combatStyle: "Area bursts, high ability scaling",
    color: "#38bdf8",
    damageKind: "magic",
    stats: {
      health: 130,
      armor: 4,
      damage: 24,
      attackSpeed: 0.9,
      range: 7.5,
      critChance: 0.12,
      critDamage: 1.65,
      abilityPower: 24,
      cooldownReduction: 0.08,
    },
    special: {
      name: "Arcane Nova",
      description: "Every third cast splashes into a small pack.",
      everyNthAttack: 3,
      cleaveTargets: 5,
      damageMultiplier: 0.88,
    },
  },
  {
    id: "ranger",
    name: "Ranger",
    fantasy: "A precise ranged fighter who deletes targets before they arrive.",
    combatStyle: "Long range, frequent critical hits",
    color: "#22c55e",
    damageKind: "ranged",
    stats: {
      health: 150,
      armor: 6,
      damage: 28,
      attackSpeed: 1.25,
      range: 9,
      critChance: 0.28,
      critDamage: 2.05,
      abilityPower: 0,
      cooldownReduction: 0.02,
    },
    special: {
      name: "Piercing Volley",
      description: "Every fifth shot punches through a line of enemies.",
      everyNthAttack: 5,
      cleaveTargets: 3,
      damageMultiplier: 0.95,
    },
  },
  {
    id: "summoner",
    name: "Summoner",
    fantasy: "A battlefield caller who overwhelms attackers with conjured allies.",
    combatStyle: "Steady chip damage, many visual allies later",
    color: "#a855f7",
    damageKind: "summon",
    stats: {
      health: 145,
      armor: 5,
      damage: 18,
      attackSpeed: 1.05,
      range: 6,
      critChance: 0.1,
      critDamage: 1.5,
      abilityPower: 18,
      cooldownReduction: 0.06,
    },
    special: {
      name: "Spirit Pack",
      description: "Every third command sends spirits at multiple enemies.",
      everyNthAttack: 3,
      cleaveTargets: 4,
      damageMultiplier: 0.7,
    },
  },
  {
    id: "guardian",
    name: "Guardian",
    fantasy: "A shielded defender who survives pressure and crushes close targets.",
    combatStyle: "High armor, stable melee damage",
    color: "#f59e0b",
    damageKind: "melee",
    stats: {
      health: 240,
      armor: 21,
      damage: 23,
      attackSpeed: 0.95,
      range: 1.9,
      critChance: 0.1,
      critDamage: 1.55,
      abilityPower: 0,
      cooldownReduction: 0,
    },
    special: {
      name: "Shield Slam",
      description: "Every fourth attack hits a small cluster while holding the line.",
      everyNthAttack: 4,
      cleaveTargets: 3,
      damageMultiplier: 0.9,
    },
  },
];

export const enemies: Record<string, EnemyDefinition> = {
  skeleton: {
    id: "skeleton",
    name: "Skeleton",
    health: 34,
    armor: 2,
    damage: 2,
    attackSpeed: 0.35,
    moveSpeed: 1.2,
    rewardXp: 5,
    rewardGold: 3,
  },
};

export const starterLevel: LevelDefinition = {
  id: "level-1",
  name: "Level 1",
  subtitle: "The Bone Gate",
  durationLimit: 45,
  seed: 1729,
  enemyWaves: [
    { enemyId: "skeleton", count: 10, startsAt: 0, interval: 0.8, gate: "north" },
    { enemyId: "skeleton", count: 8, startsAt: 4, interval: 0.75, gate: "east" },
    { enemyId: "skeleton", count: 12, startsAt: 8, interval: 0.55, gate: "west" },
  ],
};
